# Generated by Django 3.1.4 on 2020-12-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='criado',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
